# Generated by Django 3.0.5 on 2020-05-23 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200523_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 23, 16, 8, 39, 447482)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 23, 16, 8, 39, 446480)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 23, 16, 8, 39, 447482)),
        ),
    ]
