# Generated by Django 3.0.3 on 2020-03-18 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('idUtil', models.IntegerField(primary_key=True, serialize=False)),
                ('typeCompte', models.CharField(max_length=8)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=100)),
                ('mdp', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Horaires',
            fields=[
                ('idHoraires', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=100)),
                ('idUtil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.Utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('idMessage', models.IntegerField(primary_key=True, serialize=False)),
                ('texteMessage', models.CharField(max_length=5000)),
                ('idUtil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.Utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Annonces',
            fields=[
                ('idAnnonces', models.IntegerField(primary_key=True, serialize=False)),
                ('texteAnnonce', models.CharField(max_length=10000)),
                ('idUtil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.Utilisateur')),
            ],
        ),
    ]
